### ISSUE TITLE
Foxreplace Isn't Working

### ISSUE THREAD

**Issue by sdoeden** [Woundorf/foxreplace#183]
I'm a huge fan of this add-on, but it has stopped working for me today. I have made sure my version of Firefox is compatible (v48.0.2), and have tried disabling/re-enabling, using different lists, and just hitting shift-F9 over and over, but nothing seems to work. Is there a quick fix for this?

**Comment by sdoeden** [comment]
Also, just using the Foxreplace bar at the bottom of the screen, I'm met with the error message "ReferenceError: can't access lexical declaration 'oldValue' before initialization."

**Comment by KontrollierenGitHub** [comment]
The same issue: Foxreplace stopped working. Been using it for years, without any issue. Yesterday suddenly stopped working. Win 10 Pro, Firefox v. 49.0.1, Foxreplace v. 0.17.2.
Please help!

**Comment by Woundorf** [comment]
Sorry for the inconvenience, I'm looking into it right now.

**Comment by sdoeden** [comment]
It seems to just be the new version. I've applied the older version of FoxReplace from https://addons.mozilla.org/en-US/firefox/addon/foxreplace/versions/, and it seems to be working now. May just be a small bug in the new script?

**Comment by Woundorf** [comment]
Sure, but now I'm trying to reproduce the problem but it seems to work. Do you have a specific example (e.g. a page and a substitution) where it fails?

**Comment by sdoeden** [comment]
Facebook is a good example. While making a status update, I can't use FoxReplace to change anything until after I've posted. Using the Replace bar at the bottom of the page changes text, but I still get the error message, and when I click back into the status box all the changes come back. I am also unable to use my lists to change content throughout the Facebook page, lists don't work at all on editable content. Hope this helps! 

    On Thursday, September 29, 2016 10:59 AM, Marc Ruiz <notifications@github.com> wrote:
 

 Sure, but now I'm trying to reproduce the problem but it seems to work. Do you have a specific example (e.g. a page and a substitution) where it fails?—

**Comment by Woundorf** [comment]
It should now be fixed. Can you try the 0.17.3 version from https://addons.mozilla.org/firefox/addon/foxreplace/versions/ to verify it?

**Comment by sdoeden** [comment]
I can see that it's available, but I'm not able to install it. I've tried changing my configuration for xpinstall.signatures.required to false, but I still can't get it. Is there a step I'm missing? 

    On Thursday, September 29, 2016 1:30 PM, Marc Ruiz <notifications@github.com> wrote:
 

 It should now be fixed. Can you try the 0.17.3 version from https://addons.mozilla.org/firefox/addon/foxreplace/versions/ to verify it?—

**Comment by Woundorf** [comment]
It can't be installed in stable or beta versions. You can try Firefox Developer Edition which won't replace your normal install. Or just wait until it's reviewed (should take between 24 and 48 hours).

**Comment by sdoeden** [comment]
Ok, I'll wait a bit and try it out tomorrow. Thanks!

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 29, 2016 at 2:14 PM, Marc Ruiz<notifications@github.com> wrote:   
It can't be installed in stable or beta versions. You can try Firefox Developer Edition which won't replace your normal install. Or just wait until it's reviewed (should take between 24 and 48 hours).

**Comment by sdoeden** [comment]
What's the longest you've had to wait to get an add on signed?

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 29, 2016 at 2:16 PM, Shaun Doeden<shaundoeden@yahoo.com> wrote:   Ok, I'll wait a bit and try it out tomorrow. Thanks!

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 29, 2016 at 2:14 PM, Marc Ruiz<notifications@github.com> wrote:   
It can't be installed in stable or beta versions. You can try Firefox Developer Edition which won't replace your normal install. Or just wait until it's reviewed (should take between 24 and 48 hours).

**Comment by Woundorf** [comment]
Years ago it could take several days, but recently it always took 1 or 2 days. Now it's one week already since I published the latest version and I'm still waiting.
