### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by Omwrecker** [Woundorf/foxreplace#222]
Currently the export button doesn't work for me. I don't know if it has something to do with the length of my list or something else. The list and backup list on the /appdata/roaming folder is only from the previous version so I don't know where the new FoxReplace saves the new list data.

It does download something, but it just gives Failed - blob resource

**Comment by standoski** [comment]
Yep, I subscribe to this problem. The Export option not working in 1.1.3 under FF 55.0.3

**Comment by Woundorf** [comment]
Now I see that it also fails for me, although it worked in development.

**Comment by MarkMcDe** [comment]
Yup, I'm having the same issue (running on a MacBook, FF ver 55.0.3). I found a workaround for if you really, really need to access the FoxPeplace.json file: Do a "Refresh" on Firefox. Of course, it blows out all your settings and add-ons, but the "Old Firefox Data" folder it creates will have your full .json file. And it foxed the problem #233 by resetting "Multiprocess" so the FR screen doesn't stick on "Loading."

**Comment by JohnFHall** [comment]
FF 56.0 on MacPRO 10.11.6 also fails Export. Download reports "Failed - blob resource"

**Comment by Woundorf** [comment]
Fixed in f3c238b.

**Comment by sqgl2** [comment]
Still does not work for me. It pretends to export but there is no file written. The firefox downloads page says it failed calling it a "blob resource". My FoxReplace file is huge so perhaps that is why.

Have installed latest FF56.0.2 64bit and FR1.1.3 with a yellow "Legacy" label next to it on the Add-ons tab and when I check the Mozilla FR download page I am told you need FF57.0 or greater (even though it does not exist). I have not idea which version of FR "f3c238b" refers to.

**Comment by Woundorf** [comment]
That is not a version but a commit hash (don't worry if you don't understand this, it's only for me to know where I fixed it).

The fix is incorporated in version 2.0.0 which needs Firefox 57 which is currently in beta. Thus you should install the beta or wait 10 days until the stable version of Firefox 57 is out.

**Comment by ctrl-qcvh** [comment]
HI MARK!!!!!
